environments:
  dev:
    backend_port: 3005
    frontend_port: 8081
    nginx_http_port: 8080
    nginx_https_port: 8443
    domain: "dev.ruthi.in"
    db_name: "dev"
  qa:
    backend_port: 3006
    frontend_port: 8082
    nginx_http_port: 9080
    nginx_https_port: 9443
    domain: "qa.ruthi.in"
    db_name: "qa"
  prod:
    backend_port: 3007
    frontend_port: 8083
    nginx_http_port: 80
    nginx_https_port: 443
    domain: "ruthi.in"
    db_name: "prod"